# --- NETWORK CONFIGURATION ---
[Net.ServicePointManager]::SecurityProtocol = [Net.SecurityProtocolType]::Tls12

# --- CONFIGURATION ---
$githubUser = "0xAntoni0"
$githubRepo = "LetThereBeScript"
$branch     = "main"  # Change to 'master' if needed

# We point to the raw JSON file generated by your GitHub Action
$jsonUrl = "https://raw.githubusercontent.com/$githubUser/$githubRepo/$branch/scripts.json"

Clear-Host
Write-Host "Fetching script inventory..." -ForegroundColor Cyan

try {
    # 1. DOWNLOAD INVENTORY
    # We add a random number (?v=...) to bypass local caching and always get the latest version
    $rand = Get-Random
    $inventory = Invoke-RestMethod -Uri "$jsonUrl`?v=$rand" -ErrorAction Stop

    # Check if inventory is valid
    if ($inventory.Count -eq 0) {
        Write-Warning "Inventory file (scripts.json) is empty."
        exit
    }

    # --- MENU DISPLAY ---
    Write-Host "`n--- AVAILABLE SCRIPTS ---" -ForegroundColor Yellow
    
    for ($i = 0; $i -lt $inventory.Count; $i++) {
        $item = $inventory[$i]
        
        # Display: [Number] Filename
        Write-Host "[$($i+1)] $($item.filename)" -ForegroundColor White
        
        # Display: Description (from .SYNOPSIS)
        Write-Host "     └─ $($item.description)" -ForegroundColor DarkGray
    }

    Write-Host ""
    $selection = Read-Host "Enter the number of the script to run"

    # --- VALIDATION & EXECUTION ---
    if ($selection -match "^\d+$") {
        $num = [int]$selection
        
        if ($num -gt 0 -and $num -le $inventory.Count) {
            
            # Get the selected object from JSON
            $chosen = $inventory[$num - 1]
            
            Write-Host "`nLaunching: $($chosen.filename)..." -ForegroundColor Green
            
            # 2. EXECUTE
            # We use 'url_raw' which was pre-calculated by the GitHub Action
            Invoke-WebRequest -Uri $chosen.url_raw -UseBasicParsing | Invoke-Expression
            
        } else {
            Write-Error "Number out of range."
        }
    } else {
        Write-Error "Invalid input. Please enter a number."
    }

} catch {
    Write-Error "Could not load scripts.json."
    Write-Error "Make sure the GitHub Action has run successfully at least once."
    Write-Error "Error details: $_"
}
